services:
  app:
    build: .
    container_name: web_store_gensystem
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app/
      - /app/node_modules/
    environment:
      - PORT=${PORT}
      - NODE_ENV=development
      - URL=${URL}
    command: npx nodemon --legacy-watch /app/src/index.js